<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12"> 
             <form action="<?= $this->action ?>" method="POST" role="form">
                <div class="col-md-4">
                <div class="form-group">
                <label>Categoria:</label>
                   <select name='service[categories_id]' class="form-control">
                    <option value=''>Selecione uma categoria</option>
                    <?php foreach(Category::all() as $category) {?>
                       <option value='<?= $category->getId() ?>'
                          <?= ($category->getId() === $this->service->getCategoriesId()) ? 'selected' : '' ?> >
                          <?= $category->getDescription() ?>
                       </option>
                    <?php } ?>
                </select>
              </div>
            </div>
              <div class="col-md-7">
                <?= create_input_field($this->service, 'service','name', 'Nome do serviço: ', 'Digite o nome do serviço')?>
              </div>
              <div class="col-md-10">
                <?= create_text_field($this->service, 'service','description', 'Descrição: ', '')?>
              </div>
              <div class="col-md-3">
                <?= create_input_field($this->service, 'service','cost', 'Valor: ', 'Informe valor total')?>
              </div>
              <div style="clear: both"></div>
                <div class="floatright">
                  <button type="submit" class="btn btn-primary"><?= $this->submit ?></button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
