<section>
  <header>
    <h2> <?= $this->title ?></h2>
    <hr>
  </header>
  	<div class="panel panel-default">
    	<table class="table table-striped table-bordered table-advance table-hover">
	  	  <thead>
	  		<tr>
			  <th><i class="fa fa-folder-open"></i> ID </th>
			  <th><i class="fa fa-laptop"></i> Serviço </th>
			  <th><i class="fa fa-pencil"></i> Descrição </th>
			  <th><i class="fa fa-dollar"></i> Valor </th>
			  <th><i class="fa fa-list"></i> Categoria </th>
			</tr>
		  </thead>
		  <tbody>
		  	<tr>
		  		<td><?= $this->service->getId() ?></td>
		  		<td><?= $this->service->getName() ?></td>
		  		<td><?= $this->service->getDescription() ?></td>
		  		<td><?= $this->service->getCost() ?></td>
		  		<td><?= $this->service->getCategory()->getDescription() ?></td>
		  	</tr>
		  </tbody>
		</table>
	</div>
</section>
<div class="row">
  	<div class="floatright">
  		<?= link_to('/servicos', 'Voltar', ' class="btn btn-primary"') ?>
  	</div>
</div>