<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                    <h2>Cadastro de cliente fisico</h2>
                    <hr>
                    <form action="<?= $this->action ?>" method="POST" role="form" name="form1">
                        <div class="col-md-8">
                           <?= create_input_field($this->clientp, 'clientp','name', 'Nome: ', 'Digite o nome do cliente' )?>
                        </div>
                        <div class="col-md-4">
                           <?= create_input_field($this->clientp, 'clientp','cpf', 'CPF: ', 'Digite o CPF' )?>
                        </div>
                        <div class="col-md-8">
                            <?= create_radio_field($this->clientp, 'clientp', 'genre', 'Sexo: ', array('M' => 'Masculino', 'F' => 'Feminino'), 'inline') ?>
                        </div>
                        <div class="col-md-5">
                            <?= create_select_field($this->clientp, 'clientp', 'cities_id', 'Cidades: ', 'Selecione uma cidade',City::all(), $this->clientp->getCitiesId(),  true, array('value' => 'id', 'view' => 'name')); ?>
                        </div>
                        <div class="col-md-9">
                            <?= create_input_field($this->clientp, 'clientp','address', 'Endereço: ', '')?>
                        </div>
                        <div class="col-md-4">
                            <?= create_input_field($this->clientp, 'clientp','phone', 'Telefone: ', 'Digite o número do telefone' )?>
                        </div>
                        <div class="col-md-8">
                            <?= create_input_field($this->clientp, 'clientp','email', 'Email: ', '')?>
                        </div>
                        <div class="col-md-8">
                            <?= create_hidden_field('clientp', 'client_type', 'F') ?>
                        </div>
                        <div style="clear: both">
                            <div class="floatright">
                                <button type="submit" class="btn btn-primary"><?= $this->submit ?></button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
