<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">
                Toggle navigation
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
        </button>   
        <?= link_to('/', '<img class="logo" src="'.ASSETS_FOLDER.'/img/logo.png">', 'class="navbar-brand"'); ?> 
    </div>
    <div class="login">
            <?php if (isset($_SESSION['user'])): ?>
                <form action="<?= $this->urlFor('/logout') ?>" method="POST">
                    <p> <strong> Olá, </strong> <?= $_SESSION['user']['name'] ?>&nbsp;&nbsp;
                    <button type="submit" class="btn btn-primary">Sair</button> </p>
                </form>
            <?php elseif (! active_class('/login.*')): ?>
                <form class="navbar-form navbar-right top-login" action="<?= $this->urlFor('/login') ?>" method="POST">
                    <div class="form-group">
                      <input type="text" placeholder="Email" class="form-control" name="user_session[email]">
                    </div>
                    <div class="form-group">
                      <input type="password" placeholder="Password" class="form-control" name="user_session[password]">
                    </div>
                    <button type="submit" class="btn btn-success">Logar</button>
                </form>
            <?php endif ?>
    </div>
</nav>