<div class="panel panel-default">
    <div class="panel-body">
        <div class="form-group">
            <div class="logo-2">
                <img class="logo" src="<?= ASSETS_FOLDER ?>/img/logo.png">
            </div>
        </div>
        <div class="img-adjust">
            <h4>Infotech Informática</h4>
            <h5>Rua XV de Novembro, 589. Guarapuava - PR</h5>
            <h6>www.infotec.com.br</h6>
        </div>
        <hr>

        <div class="panel panel-default">
            <div class="panel-heading text-center">
                <h4>Dados da Ordem de Serviço</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th><i class="fa fa-folder-open"></i> Número da O.S. </th>
                            <th><i class="fa fa-flag"></i> Problema Relatado </th>
                            <th><i class="fa fa-exclamation"></i> Observação </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?= $this->service_order->getId() ?></td>
                            <td><?= $this->service_order->getReportedProblem() ?></td>
                            <td><?= $this->service_order->getObservation() ?><br></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <form action="<?= $this->action_add ?>" method="POST">
            <?= create_hidden_field('item_service', 'service_orders_id', $this->service_order->getId())?>
          <div class="col-md-4">
            <?= create_select_field('', 'item_service', 'services_id', 'Adicionar serviço: ', 'Selecione um serviço',Service::all(), '',  true, array('value' => 'id', 'view' => 'name')); ?>
          </div>
          <div style="padding-top:25px;">
            <button type="submit" class="btn btn-primary"><?= $this->submit_add ?></button>
          </div>
        </form>
        <br><br>

        <div class="panel panel-default">
            <div class="panel-heading text-center">
                <h4>Lista de serviços</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th><i class="fa fa-laptop"></i> Nome do Serviço</th>
                            <th><i class="fa fa-pencil"></i> Descrição</th>
                            <th><i class="fa fa-list"></i> Categoria</th>
                            <th><i class="fa fa-dollar"></i> Valor Unitário</th>
                            <th><i class="fa fa-cogs"></i> Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->items_services as $item_service):?>
                        <tr>
                            <td><?= $item_service->getService()->getName() ?></td>
                            <td><?= $item_service->getService()->getDescription() ?></td>
                            <td><?= $item_service->getService()->getCategory()->getDescription()  ?></td>
                            <td>R$ <?= $item_service->getService()->getCost() ?></td>
                            <td><?= link_to("/ordens-servicos/items-servicos/{$item_service->getId()}/{$this->service_order->getId()}/deletar", 'Excluir', 'data-confirm="Tem Certeza?"') ?>
                            </td>
                        </tr>
                    <?php endforeach?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <?= link_to('/ordens-servicos/'.$this->service_order->getId(), 'Voltar para a ordem de serviço', 'class="btn btn-primary"') ?>
          <div class="floatright">
            <?= link_to('/ordens-servicos/'.$this->service_order->getId(), 'Finalizar', ' class="btn btn-primary"') ?>
          </div>
        </div>
    </div>
</div>