<section>
  <header>
    <h2> <?= $this->title ?> </h2>
    <hr>
  </header>
</section>	
<div class="panel panel-default">
  <table class="table table-striped table-advance table-hover">
      <tbody>
          <tr>
            <th><i class="fa fa-user"></i> Técnico</th>
            <th><i class="fa fa-flag"></i> Número total de ordens</th>
            <th><i class="fa fa-cogs"></i> Ordens Novas</th>
            <th><i class="fa fa-cogs"></i> Ordens Concluídas</th>
            <th><i class="fa fa-cogs"></i> Ordens Abertas</th>
            <th><i class="fa fa-cogs"></i> Ordens Aprovadas</th>
            <th><i class="fa fa-cogs"></i> Ordens Reprovadas</th>
            <th><i class="fa fa-cogs"></i> Ordens Canceladas</th>
          </tr>
          <?php foreach ($this->reports as $report):?>
            <tr>
                <td><?= link_to('/relatorios/'.$report->getEmployeesId() ,$report->getEmployee()->getName()) ?></td>
                <td><?= $report->getTotalOrders() ?></td>
           <!-- AQUI VOCÊ PEGA O FUNCIONÁRIO LOGADO NO SISTEMA E MOSTRA AS ORDENS DE SERVIÇO DELE!  -->
                <td><?= $report->getAmountBySituationId(1) ?></td>
                <td><?= $report->getAmountBySituationId(4) ?></td>
                <td><?= $report->getAmountBySituationId(2) ?></td>
                <td><?= $report->getAmountBySituationId(3) ?></td>
                <td><?= $report->getAmountBySituationId(5) ?></td>
                <td><?= $report->getAmountBySituationId(6) ?></td>
            </tr>
            <?php endforeach?>
      </tbody>
  </table>
</div>